name: Martin Lass - Violinist
favicon: null
layout_spectrum: 0.89882
typography_spectrum: 0.73275
title: Martin Lass - Violinist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0a10'
    - '#7a9acb'
    - '#e1dfe0'
    - '#3d404f'
    - '#caa878'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
