name: Martin Lass - Violinist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56284
title: Martin Lass - Violinist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140001'
    - '#f5f3f8'
    - '#e7202c'
    - '#8c0c12'
    - '#c3957b'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
