name: Martin Lass - Violinist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56284
title: Martin Lass - Violinist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7dcdc3'
    - '#3f3f3f'
    - '#eba485'
    - '#929292'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
