name: Martin Lass - Violinist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04937
title: Martin Lass - Violinist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0e0f'
    - '#cfbbcd'
    - '#4a3837'
    - '#004c8b'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
