name: Martin Lass - Violinist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56284
title: Martin Lass - Violinist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9e3e5'
    - '#0d111a'
    - '#adb9ce'
    - '#767e8a'
    - '#a65330'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
