name: Martin Lass - Violinist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83392
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0e0f'
    - '#cfbbcd'
    - '#4a3837'
    - '#004c8b'
  brandStrength: 0.8600207895506173
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
